### PR TITLE
Search error alex Closed #17

### LINKED ISSUE #17: Return error message after no results
DOD: an error message will pop up under the search bar showing that no results were found

### PR DESCRIPTION
**Pull request by AlexKSparks**
So this view error is supposed to pop up in both the advanced search and the basic search if either return no results. With no basic search logic, I can't think of a way to display the error message on basic search. Is it okay if a basic search fails, it gets rerouted to the advanced search with an error message?

### CODE REVIEW

**Review by ksdurg — APPROVED** [review]
Looks good.

**Comment by adamkohler** [comment]
Yes, I think having the basic search fail be rerouted to advanced search is fine.  We may need to change this down the road but I think your right since we merged the basic and advanced search this may be the only option.

**Review by adamkohler — APPROVED** [review]

**Review by Daniel-Watkins — APPROVED** [review]
Looks fine.

**Review by keithrutler — APPROVED** [review]
looks good

**Pull request merged**
