### PR TITLE
BasicSearchLogic-Adam Closed #24

### LINKED ISSUE #24: Logic for basic search
DOD: implementation of basic search logic for athletes

### PR DESCRIPTION
**Pull request by adamkohler**
basic search logic for a coach to search for athletes.  We will probably decide to move this into the same location as Daniel's logic in the SearchController.

### CODE REVIEW

**Comment by adamkohler** [comment]
Move basicsearch method to SearchController.cs
create post method similar to daniel's
[get] basicsearch method

**Review by AlexKSparks — APPROVED** [review]

**Comment by adamkohler** [comment]
Should be all set to merge, removed logic from coach controller

**Review by ksdurg — COMMENTED** [review]
what is the functional difference between the last two if statements?  Your comments make it sound like they are supposed to do the same thing ... list all athletes.  if you use if(athletes.Position == null) then won't that possibly just use if statements further up in the code?

**Comment by Daniel-Watkins** [comment]
Kevin, what if statements are you referring to?

**Review by Daniel-Watkins — APPROVED** [review]
Looks good to me.

**Comment by ksdurg** [comment]
Daniel, I'm not sure now.  I can't seem to find the file from Adam that I was looking at previously.  I thought it was some basic search logic that Adam had wrote.  The statements started at around line 200.  No clue why I can't find it in this issue now.

**Comment by ksdurg** [comment]
I wasn't added as a reviewer, but I think it looks good nonetheless.

**Comment by adamkohler** [comment]
The stuff you were looking at Kevin was an older file.  I had to remove the search logic from the coach controller.  Daniel's advanced search logic also covered the basic search logic, so we ended up not needed an extra method to handle a basic search.  What I did add was the get/set for a basic search that would route to the correct view and re-direct to Daniels search method if the model was valid.

**Review by AlexKSparks — APPROVED** [review]

**Review by keithrutler — APPROVED** [review]
Looks good

**Pull request merged**
