### PR TITLE
Search results view daniel

### PR DESCRIPTION
**Pull request by Daniel-Watkins**
I added a viewmodel called SearchResultsViewModel to a new model subfolder called SearchViewModel. I also added a view called SearchResults to a new view subfolder called Search. This view should display all results from a search in a table format. I have yet to add links or buttons that can take you to each athletes profile from the results page. I also added SearchResults to ManageNavPages file. The purpose of this pull request is for review before the progress report on 4/15.

### CODE REVIEW

**Review by ksdurg — COMMENTED** [review]
Everything looks good so far.  This is great work, Daniel.
I'll try to run everything in the morning just to ensure it's working (at least on my end).

**Review by ksdurg — APPROVED** [review]

**Review by AlexKSparks — APPROVED** [review]
Looks good

**Review by adamkohler — APPROVED** [review]
I like it Daniel.  Smart ideas to create a new VM as needed for the information, I had not thought of that and may utilize your idea.

**Review by keithrutler — APPROVED** [review]
The SearchResultsViewModel was a good idea, thanks for adding that to the project.

**Pull request merged**
